// Auto-generated from exercise_library_full.xlsx
// Do not edit this file manually

export interface Exercise {
  id: string
  name: string
  category: string
  muscleGroup: string
}

export const EXERCISES: Exercise[] = [
  {
    "id": "1",
    "name": "Ab Wheel",
    "category": "ABS - BODYWEIGHT ONLY",
    "muscleGroup": "Abs"
  },
  {
    "id": "2",
    "name": "Cable Rope Crunch",
    "category": "ABS - CABLE",
    "muscleGroup": "Abs"
  },
  {
    "id": "3",
    "name": "Hanging Knee Raise",
    "category": "ABS - BODYWEIGHT ONLY",
    "muscleGroup": "Abs"
  },
  {
    "id": "4",
    "name": "Hanging Straight Leg Raise",
    "category": "ABS - BODYWEIGHT ONLY",
    "muscleGroup": "Abs"
  },
  {
    "id": "5",
    "name": "Machine Crunch",
    "category": "ABS - MACHINE",
    "muscleGroup": "Abs"
  },
  {
    "id": "6",
    "name": "Reaching Sit-Up",
    "category": "ABS - BODYWEIGHT ONLY",
    "muscleGroup": "Abs"
  },
  {
    "id": "7",
    "name": "V-Up (Weighted)",
    "category": "ABS - BODYWEIGHT LOADABLE",
    "muscleGroup": "Abs"
  },
  {
    "id": "8",
    "name": "Assisted Pullup",
    "category": "BACK - MACHINE ASSISTANCE",
    "muscleGroup": "Back"
  },
  {
    "id": "9",
    "name": "Back Extension",
    "category": "BACK - BODYWEIGHT LOADABLE",
    "muscleGroup": "Back"
  },
  {
    "id": "10",
    "name": "Barbell Bent Over Row",
    "category": "BACK - BARBELL",
    "muscleGroup": "Back"
  },
  {
    "id": "11",
    "name": "Barbell Flexion Row",
    "category": "BACK - BARBELL",
    "muscleGroup": "Back"
  },
  {
    "id": "12",
    "name": "Barbell Row To Chest",
    "category": "BACK - BARBELL",
    "muscleGroup": "Back"
  },
  {
    "id": "13",
    "name": "Cable Flexion Row",
    "category": "BACK - CABLE",
    "muscleGroup": "Back"
  },
  {
    "id": "14",
    "name": "Cable Pullover",
    "category": "BACK - CABLE",
    "muscleGroup": "Back"
  },
  {
    "id": "15",
    "name": "Cambered Bar Row",
    "category": "BACK - BARBELL",
    "muscleGroup": "Back"
  },
  {
    "id": "16",
    "name": "Chest Supported Row",
    "category": "BACK - MACHINE",
    "muscleGroup": "Back"
  },
  {
    "id": "17",
    "name": "Deadlift",
    "category": "BACK - BARBELL",
    "muscleGroup": "Back"
  },
  {
    "id": "18",
    "name": "Dumbbell Pullover",
    "category": "BACK - DUMBBELL",
    "muscleGroup": "Back"
  },
  {
    "id": "19",
    "name": "Dumbbell Row (2-Arm)",
    "category": "BACK - DUMBBELL",
    "muscleGroup": "Back"
  },
  {
    "id": "20",
    "name": "Dumbbell Row (Single-Arm, Supported)",
    "category": "BACK - DUMBBELL",
    "muscleGroup": "Back"
  },
  {
    "id": "21",
    "name": "Hammer Machine Pulldown (Underhand)",
    "category": "BACK - MACHINE",
    "muscleGroup": "Back"
  },
  {
    "id": "22",
    "name": "Inverted Row",
    "category": "BACK - BODYWEIGHT ONLY",
    "muscleGroup": "Back"
  },
  {
    "id": "23",
    "name": "Landmine Row",
    "category": "BACK - BARBELL",
    "muscleGroup": "Back"
  },
  {
    "id": "24",
    "name": "Machine Chest Supported Row",
    "category": "BACK - MACHINE",
    "muscleGroup": "Back"
  },
  {
    "id": "25",
    "name": "Machine Pulldown",
    "category": "BACK - MACHINE",
    "muscleGroup": "Back"
  },
  {
    "id": "26",
    "name": "Machine Pullover",
    "category": "BACK - MACHINE",
    "muscleGroup": "Back"
  },
  {
    "id": "27",
    "name": "Lat Pulldown (Narrow Grip)",
    "category": "BACK - CABLE",
    "muscleGroup": "Back"
  },
  {
    "id": "28",
    "name": "Lat Pulldown (Normal Grip)",
    "category": "BACK - CABLE",
    "muscleGroup": "Back"
  },
  {
    "id": "29",
    "name": "Lat Pulldown (Single-Arm)",
    "category": "BACK - CABLE",
    "muscleGroup": "Back"
  },
  {
    "id": "30",
    "name": "Lat Pulldown (Wide Grip)",
    "category": "BACK - CABLE",
    "muscleGroup": "Back"
  },
  {
    "id": "31",
    "name": "Pullup (Normal Grip)",
    "category": "BACK - BODYWEIGHT ONLY",
    "muscleGroup": "Back"
  },
  {
    "id": "32",
    "name": "Pullup (Neutral Grip)",
    "category": "BACK - BODYWEIGHT ONLY",
    "muscleGroup": "Back"
  },
  {
    "id": "33",
    "name": "Pullup (Underhand Grip)",
    "category": "BACK - BODYWEIGHT ONLY",
    "muscleGroup": "Back"
  },
  {
    "id": "34",
    "name": "Pullup (Weighted, Normal Grip)",
    "category": "BACK - BODYWEIGHT LOADABLE",
    "muscleGroup": "Back"
  },
  {
    "id": "35",
    "name": "Pullup (Weighted, Neutral  Grip)",
    "category": "BACK - BODYWEIGHT LOADABLE",
    "muscleGroup": "Back"
  },
  {
    "id": "36",
    "name": "Pullup (Weighted, Underhand Grip)",
    "category": "BACK - BODYWEIGHT LOADABLE",
    "muscleGroup": "Back"
  },
  {
    "id": "37",
    "name": "Rear Delt Fly",
    "category": "BACK - MACHINE",
    "muscleGroup": "Back"
  },
  {
    "id": "38",
    "name": "Seal Row",
    "category": "BACK - BARBELL",
    "muscleGroup": "Back"
  },
  {
    "id": "39",
    "name": "Seated Cable Row",
    "category": "BACK - CABLE",
    "muscleGroup": "Back"
  },
  {
    "id": "40",
    "name": "Seated Cable Row (Single-Arm)",
    "category": "BACK - CABLE",
    "muscleGroup": "Back"
  },
  {
    "id": "41",
    "name": "Single Arm Cable Pull Down (45 Degree)",
    "category": "BACK - CABLE",
    "muscleGroup": "Back"
  },
  {
    "id": "42",
    "name": "Smith Machine Row",
    "category": "BACK - SMITH MACHINE",
    "muscleGroup": "Back"
  },
  {
    "id": "43",
    "name": "T-Bar Row",
    "category": "BACK - MACHINE",
    "muscleGroup": "Back"
  },
  {
    "id": "44",
    "name": "Barbell Curl (Narrow Grip)",
    "category": "BICEPS - BARBELL",
    "muscleGroup": "Biceps"
  },
  {
    "id": "45",
    "name": "Barbell Curl (Normal Grip)",
    "category": "BICEPS - BARBELL",
    "muscleGroup": "Biceps"
  },
  {
    "id": "46",
    "name": "Bayesian Curl",
    "category": "BICEPS - CABLE",
    "muscleGroup": "Biceps"
  },
  {
    "id": "47",
    "name": "Cable Curl",
    "category": "BICEPS - CABLE",
    "muscleGroup": "Biceps"
  },
  {
    "id": "48",
    "name": "Cable Curl (Ez Bar)",
    "category": "BICEPS - CABLE",
    "muscleGroup": "Biceps"
  },
  {
    "id": "49",
    "name": "Cable Curl (Single-Arm)",
    "category": "BICEPS - CABLE",
    "muscleGroup": "Biceps"
  },
  {
    "id": "50",
    "name": "Cable Hammer Curl",
    "category": "BICEPS - CABLE",
    "muscleGroup": "Biceps"
  },
  {
    "id": "51",
    "name": "Cable Rope Twist Curl",
    "category": "BICEPS - CABLE",
    "muscleGroup": "Biceps"
  },
  {
    "id": "52",
    "name": "Concentration Curl",
    "category": "BICEPS - DUMBBELL",
    "muscleGroup": "Biceps"
  },
  {
    "id": "53",
    "name": "Dumbbell Curl (2-Arm)",
    "category": "BICEPS - DUMBBELL",
    "muscleGroup": "Biceps"
  },
  {
    "id": "54",
    "name": "Dumbbell Curl (Alternating)",
    "category": "BICEPS - DUMBBELL",
    "muscleGroup": "Biceps"
  },
  {
    "id": "55",
    "name": "Dumbbell Curl (Incline)",
    "category": "BICEPS - DUMBBELL",
    "muscleGroup": "Biceps"
  },
  {
    "id": "56",
    "name": "Dumbbell Preacher Curl (Single-Arm)",
    "category": "BICEPS - DUMBBELL",
    "muscleGroup": "Biceps"
  },
  {
    "id": "57",
    "name": "Dumbbell Spider Curl",
    "category": "BICEPS - DUMBBELL",
    "muscleGroup": "Biceps"
  },
  {
    "id": "58",
    "name": "Ez Bar Curl (Narrow Grip)",
    "category": "BICEPS - BARBELL",
    "muscleGroup": "Biceps"
  },
  {
    "id": "59",
    "name": "Ez Bar Curl (Normal Grip)",
    "category": "BICEPS - BARBELL",
    "muscleGroup": "Biceps"
  },
  {
    "id": "60",
    "name": "Ez Bar Preacher Curl",
    "category": "BICEPS - BARBELL",
    "muscleGroup": "Biceps"
  },
  {
    "id": "61",
    "name": "Ez Bar Spider Curl",
    "category": "BICEPS - BARBELL",
    "muscleGroup": "Biceps"
  },
  {
    "id": "62",
    "name": "Hammer Curl",
    "category": "BICEPS - DUMBBELL",
    "muscleGroup": "Biceps"
  },
  {
    "id": "63",
    "name": "Hammer Preacher Curl",
    "category": "BICEPS - DUMBBELL",
    "muscleGroup": "Biceps"
  },
  {
    "id": "64",
    "name": "Machine Preacher Curl",
    "category": "BICEPS - MACHINE",
    "muscleGroup": "Biceps"
  },
  {
    "id": "65",
    "name": "Machine Preacher Curl (Single Arm)",
    "category": "BICEPS - MACHINE",
    "muscleGroup": "Biceps"
  },
  {
    "id": "66",
    "name": "Reverse Ez Bar Curl",
    "category": "BICEPS - BARBELL",
    "muscleGroup": "Biceps"
  },
  {
    "id": "67",
    "name": "Calf Machine",
    "category": "CALVES - MACHINE",
    "muscleGroup": "Calves"
  },
  {
    "id": "68",
    "name": "Calf Raises",
    "category": "CALVES - MACHINE",
    "muscleGroup": "Calves"
  },
  {
    "id": "69",
    "name": "Leg Press Calves",
    "category": "CALVES - MACHINE",
    "muscleGroup": "Calves"
  },
  {
    "id": "70",
    "name": "Smith Machine Calves",
    "category": "CALVES - SMITH MACHINE",
    "muscleGroup": "Calves"
  },
  {
    "id": "71",
    "name": "Standing Calf Raise",
    "category": "CALVES - MACHINE",
    "muscleGroup": "Calves"
  },
  {
    "id": "72",
    "name": "Bench Press (Decline)",
    "category": "CHEST - BARBELL",
    "muscleGroup": "Chest"
  },
  {
    "id": "73",
    "name": "Bench Press (Incline)",
    "category": "CHEST - BARBELL",
    "muscleGroup": "Chest"
  },
  {
    "id": "74",
    "name": "Bench Press (Flat)",
    "category": "CHEST - BARBELL",
    "muscleGroup": "Chest"
  },
  {
    "id": "75",
    "name": "Cable Chest Press",
    "category": "CHEST - CABLE",
    "muscleGroup": "Chest"
  },
  {
    "id": "76",
    "name": "Cable Flye",
    "category": "CHEST - CABLE",
    "muscleGroup": "Chest"
  },
  {
    "id": "77",
    "name": "Cable Flye (Bent Over)",
    "category": "CHEST - CABLE",
    "muscleGroup": "Chest"
  },
  {
    "id": "78",
    "name": "Cable Flye (High)",
    "category": "CHEST - CABLE",
    "muscleGroup": "Chest"
  },
  {
    "id": "79",
    "name": "Cable Flye (Seated)",
    "category": "CHEST - CABLE",
    "muscleGroup": "Chest"
  },
  {
    "id": "80",
    "name": "Dip (Chest-Focused)",
    "category": "CHEST - BODYWEIGHT ONLY",
    "muscleGroup": "Chest"
  },
  {
    "id": "81",
    "name": "Dip (Weighted, Chest-Focused)",
    "category": "CHEST - BODYWEIGHT LOADABLE",
    "muscleGroup": "Chest"
  },
  {
    "id": "82",
    "name": "Dumbbell Flye (Flat)",
    "category": "CHEST - DUMBBELL",
    "muscleGroup": "Chest"
  },
  {
    "id": "83",
    "name": "Dumbbell Flye (Incline)",
    "category": "CHEST - DUMBBELL",
    "muscleGroup": "Chest"
  },
  {
    "id": "84",
    "name": "Dumbbell Press (Flat)",
    "category": "CHEST - DUMBBELL",
    "muscleGroup": "Chest"
  },
  {
    "id": "85",
    "name": "Dumbbell Press (Incline)",
    "category": "CHEST - DUMBBELL",
    "muscleGroup": "Chest"
  },
  {
    "id": "86",
    "name": "Dumbbell Press Flye (Flat)",
    "category": "CHEST - DUMBBELL",
    "muscleGroup": "Chest"
  },
  {
    "id": "87",
    "name": "Dumbbell Press Flye (Incline)",
    "category": "CHEST - DUMBBELL",
    "muscleGroup": "Chest"
  },
  {
    "id": "88",
    "name": "Machine Chest Press",
    "category": "CHEST - MACHINE",
    "muscleGroup": "Chest"
  },
  {
    "id": "89",
    "name": "Machine Chest Press (Incline)",
    "category": "CHEST - MACHINE",
    "muscleGroup": "Chest"
  },
  {
    "id": "90",
    "name": "Machine Flye",
    "category": "CHEST - MACHINE",
    "muscleGroup": "Chest"
  },
  {
    "id": "91",
    "name": "Pec Dec Flye",
    "category": "CHEST - MACHINE",
    "muscleGroup": "Chest"
  },
  {
    "id": "92",
    "name": "Pushup",
    "category": "CHEST - BODYWEIGHT ONLY",
    "muscleGroup": "Chest"
  },
  {
    "id": "93",
    "name": "Pushup (Deficit)",
    "category": "CHEST - BODYWEIGHT ONLY",
    "muscleGroup": "Chest"
  },
  {
    "id": "94",
    "name": "Pushup (Narrow Grip)",
    "category": "CHEST - BODYWEIGHT ONLY",
    "muscleGroup": "Chest"
  },
  {
    "id": "95",
    "name": "Pushup (Weighted, Narrow Grip)",
    "category": "CHEST - BODYWEIGHT LOADABLE",
    "muscleGroup": "Chest"
  },
  {
    "id": "96",
    "name": "Pushup (Weighted)",
    "category": "CHEST - BODYWEIGHT LOADABLE",
    "muscleGroup": "Chest"
  },
  {
    "id": "97",
    "name": "Smith Machine Bench Press",
    "category": "CHEST - SMITH MACHINE",
    "muscleGroup": "Chest"
  },
  {
    "id": "98",
    "name": "Smith Machine Press (Incline)",
    "category": "CHEST - SMITH MACHINE",
    "muscleGroup": "Chest"
  },
  {
    "id": "99",
    "name": "Smith Machine Press (Decline)",
    "category": "CHEST - SMITH MACHINE",
    "muscleGroup": "Chest"
  },
  {
    "id": "100",
    "name": "Barbell Standing Wrist Curl",
    "category": "FOREARMS - BARBELL",
    "muscleGroup": "Forearms"
  },
  {
    "id": "101",
    "name": "Cable Wrist Curl",
    "category": "FOREARMS - CABLE",
    "muscleGroup": "Forearms"
  },
  {
    "id": "102",
    "name": "Dumbbell Bench Wrist Curl",
    "category": "FOREARMS - DUMBBELL",
    "muscleGroup": "Forearms"
  },
  {
    "id": "103",
    "name": "Dumbbell Standing Wrist Curl",
    "category": "FOREARMS - DUMBBELL",
    "muscleGroup": "Forearms"
  },
  {
    "id": "104",
    "name": "Grip Roller",
    "category": "FOREARMS - MACHINE",
    "muscleGroup": "Forearms"
  },
  {
    "id": "105",
    "name": "Reverse Curl",
    "category": "FOREARMS - BARBELL",
    "muscleGroup": "Forearms"
  },
  {
    "id": "106",
    "name": "Barbell Hip Thrust",
    "category": "GLUTES - BARBELL",
    "muscleGroup": "Glutes"
  },
  {
    "id": "107",
    "name": "Barbell Squat (Sumo Stance)",
    "category": "GLUTES - BARBELL",
    "muscleGroup": "Glutes"
  },
  {
    "id": "108",
    "name": "Belt Squat (Wide Stance)",
    "category": "GLUTES - MACHINE",
    "muscleGroup": "Glutes"
  },
  {
    "id": "109",
    "name": "Bulgarian Split Squat (Glute-Focused)",
    "category": "GLUTES - DUMBBELL",
    "muscleGroup": "Glutes"
  },
  {
    "id": "110",
    "name": "Bulgarian Split Squats",
    "category": "GLUTES - SMITH MACHINE",
    "muscleGroup": "Glutes"
  },
  {
    "id": "111",
    "name": "Cable Kickback",
    "category": "GLUTES - CABLE",
    "muscleGroup": "Glutes"
  },
  {
    "id": "112",
    "name": "Cable Pull Through",
    "category": "GLUTES - CABLE",
    "muscleGroup": "Glutes"
  },
  {
    "id": "113",
    "name": "Deadlift (Conventional)",
    "category": "GLUTES - BARBELL",
    "muscleGroup": "Glutes"
  },
  {
    "id": "114",
    "name": "Deadlift (Deficit 3.5\")",
    "category": "GLUTES - BARBELL",
    "muscleGroup": "Glutes"
  },
  {
    "id": "115",
    "name": "Deadlift (Deficit 1\")",
    "category": "GLUTES - BARBELL",
    "muscleGroup": "Glutes"
  },
  {
    "id": "116",
    "name": "Deadlift (Sumo)",
    "category": "GLUTES - BARBELL",
    "muscleGroup": "Glutes"
  },
  {
    "id": "117",
    "name": "Dumbbell Hip Thrust (Single Leg)",
    "category": "GLUTES - DUMBBELL",
    "muscleGroup": "Glutes"
  },
  {
    "id": "118",
    "name": "Dumbbell Split Squat",
    "category": "GLUTES - DUMBBELL",
    "muscleGroup": "Glutes"
  },
  {
    "id": "119",
    "name": "Front Foot Elevated Smith Lunge",
    "category": "GLUTES - SMITH MACHINE",
    "muscleGroup": "Glutes"
  },
  {
    "id": "120",
    "name": "Front Foot Elevated Split Squat",
    "category": "GLUTES - DUMBBELL",
    "muscleGroup": "Glutes"
  },
  {
    "id": "121",
    "name": "Glute Bridge",
    "category": "GLUTES - DUMBBELL",
    "muscleGroup": "Glutes"
  },
  {
    "id": "122",
    "name": "Hip Abduction Machine",
    "category": "GLUTES - MACHINE",
    "muscleGroup": "Glutes"
  },
  {
    "id": "123",
    "name": "Machine Glute Kickback",
    "category": "GLUTES - MACHINE",
    "muscleGroup": "Glutes"
  },
  {
    "id": "124",
    "name": "Machine Hip Thrust",
    "category": "GLUTES - MACHINE",
    "muscleGroup": "Glutes"
  },
  {
    "id": "125",
    "name": "Reverse Hyper",
    "category": "GLUTES - MACHINE",
    "muscleGroup": "Glutes"
  },
  {
    "id": "126",
    "name": "Reverse Lunge",
    "category": "GLUTES - SMITH MACHINE",
    "muscleGroup": "Glutes"
  },
  {
    "id": "127",
    "name": "Reverse Lunge (Barbell)",
    "category": "GLUTES - BARBELL",
    "muscleGroup": "Glutes"
  },
  {
    "id": "128",
    "name": "Reverse Lunge (Dumbbell)",
    "category": "GLUTES - DUMBBELL",
    "muscleGroup": "Glutes"
  },
  {
    "id": "129",
    "name": "Single Leg Press",
    "category": "GLUTES - MACHINE",
    "muscleGroup": "Glutes"
  },
  {
    "id": "130",
    "name": "Smith Machine Split Squat",
    "category": "GLUTES - SMITH MACHINE",
    "muscleGroup": "Glutes"
  },
  {
    "id": "131",
    "name": "Step Ups (Box)",
    "category": "GLUTES - MACHINE ASSISTANCE",
    "muscleGroup": "Glutes"
  },
  {
    "id": "132",
    "name": "Trap Bar Deadlift",
    "category": "GLUTES - BARBELL",
    "muscleGroup": "Glutes"
  },
  {
    "id": "133",
    "name": "Walking Lunges (Barbell)",
    "category": "GLUTES - BARBELL",
    "muscleGroup": "Glutes"
  },
  {
    "id": "134",
    "name": "Walking Lunges (Bodyweight)",
    "category": "GLUTES - BODYWEIGHT ONLY",
    "muscleGroup": "Glutes"
  },
  {
    "id": "135",
    "name": "Walking Lunges (Dumbbell)",
    "category": "GLUTES - DUMBBELL",
    "muscleGroup": "Glutes"
  },
  {
    "id": "136",
    "name": "Back Raise (45 Degree)",
    "category": "HAMSTRINGS - BODYWEIGHT ONLY",
    "muscleGroup": "Hamstrings"
  },
  {
    "id": "137",
    "name": "Back Raise (GHD)",
    "category": "HAMSTRINGS - BODYWEIGHT ONLY",
    "muscleGroup": "Hamstrings"
  },
  {
    "id": "138",
    "name": "Barbell Good Morning",
    "category": "HAMSTRINGS - BARBELL",
    "muscleGroup": "Hamstrings"
  },
  {
    "id": "139",
    "name": "Smith Machine Good Morning",
    "category": "HAMSTRINGS - SMITH MACHINE",
    "muscleGroup": "Hamstrings"
  },
  {
    "id": "140",
    "name": "Barbell Good Morning (Safety Bar)",
    "category": "HAMSTRINGS - BARBELL",
    "muscleGroup": "Hamstrings"
  },
  {
    "id": "141",
    "name": "Dumbbell RDL",
    "category": "HAMSTRINGS - DUMBBELL",
    "muscleGroup": "Hamstrings"
  },
  {
    "id": "142",
    "name": "Dumbbell Stiff Legged Deadlift",
    "category": "HAMSTRINGS - DUMBBELL",
    "muscleGroup": "Hamstrings"
  },
  {
    "id": "143",
    "name": "Glute Ham Raise (GHD)",
    "category": "HAMSTRINGS - BODYWEIGHT ONLY",
    "muscleGroup": "Hamstrings"
  },
  {
    "id": "144",
    "name": "Landmine RDL",
    "category": "HAMSTRINGS - BARBELL",
    "muscleGroup": "Hamstrings"
  },
  {
    "id": "145",
    "name": "Lying Leg Curl",
    "category": "HAMSTRINGS - MACHINE",
    "muscleGroup": "Hamstrings"
  },
  {
    "id": "146",
    "name": "Nordic Curl",
    "category": "HAMSTRINGS - BODYWEIGHT ONLY",
    "muscleGroup": "Hamstrings"
  },
  {
    "id": "147",
    "name": "Nordic Ham Curls (GHD)",
    "category": "HAMSTRINGS - BODYWEIGHT LOADABLE",
    "muscleGroup": "Hamstrings"
  },
  {
    "id": "148",
    "name": "Seated Leg Curl",
    "category": "HAMSTRINGS - MACHINE",
    "muscleGroup": "Hamstrings"
  },
  {
    "id": "149",
    "name": "Single Leg Romanian Deadlift",
    "category": "HAMSTRINGS - DUMBBELL",
    "muscleGroup": "Hamstrings"
  },
  {
    "id": "150",
    "name": "Single-Leg Leg Curl",
    "category": "HAMSTRINGS - MACHINE",
    "muscleGroup": "Hamstrings"
  },
  {
    "id": "151",
    "name": "Stiff-Legged Deadlift",
    "category": "HAMSTRINGS - BARBELL",
    "muscleGroup": "Hamstrings"
  },
  {
    "id": "152",
    "name": "Barbell Split Squat",
    "category": "QUADS - BARBELL",
    "muscleGroup": "Quads"
  },
  {
    "id": "153",
    "name": "Barbell Squat",
    "category": "QUADS - BARBELL",
    "muscleGroup": "Quads"
  },
  {
    "id": "154",
    "name": "Barbell Squat (Narrow Stance)",
    "category": "QUADS - BARBELL",
    "muscleGroup": "Quads"
  },
  {
    "id": "155",
    "name": "Barbell Squat (Safety Bar)",
    "category": "QUADS - BARBELL",
    "muscleGroup": "Quads"
  },
  {
    "id": "156",
    "name": "Belt Squat",
    "category": "QUADS - MACHINE",
    "muscleGroup": "Quads"
  },
  {
    "id": "157",
    "name": "Bodyweight Squat",
    "category": "QUADS - BODYWEIGHT ONLY",
    "muscleGroup": "Quads"
  },
  {
    "id": "158",
    "name": "Bulgarian Split Squat (Quad)",
    "category": "QUADS - DUMBBELL",
    "muscleGroup": "Quads"
  },
  {
    "id": "159",
    "name": "Dumbbell Front Squat",
    "category": "QUADS - DUMBBELL",
    "muscleGroup": "Quads"
  },
  {
    "id": "160",
    "name": "Forward Lunges",
    "category": "QUADS - BARBELL",
    "muscleGroup": "Quads"
  },
  {
    "id": "161",
    "name": "Front Squat",
    "category": "QUADS - BARBELL",
    "muscleGroup": "Quads"
  },
  {
    "id": "162",
    "name": "Goblet Squat",
    "category": "QUADS - DUMBBELL",
    "muscleGroup": "Quads"
  },
  {
    "id": "163",
    "name": "Hack Squat",
    "category": "QUADS - MACHINE",
    "muscleGroup": "Quads"
  },
  {
    "id": "164",
    "name": "Hip Adduction",
    "category": "QUADS - MACHINE",
    "muscleGroup": "Quads"
  },
  {
    "id": "165",
    "name": "Leg Extension",
    "category": "QUADS - MACHINE",
    "muscleGroup": "Quads"
  },
  {
    "id": "166",
    "name": "Leg Press",
    "category": "QUADS - MACHINE",
    "muscleGroup": "Quads"
  },
  {
    "id": "167",
    "name": "Pause Squat",
    "category": "QUADS - BARBELL",
    "muscleGroup": "Quads"
  },
  {
    "id": "168",
    "name": "Pendulum Squat",
    "category": "QUADS - MACHINE",
    "muscleGroup": "Quads"
  },
  {
    "id": "169",
    "name": "Single Leg Extension",
    "category": "QUADS - MACHINE",
    "muscleGroup": "Quads"
  },
  {
    "id": "170",
    "name": "Single Leg Press",
    "category": "QUADS - MACHINE",
    "muscleGroup": "Quads"
  },
  {
    "id": "171",
    "name": "Sissy Squat",
    "category": "QUADS - BODYWEIGHT ONLY",
    "muscleGroup": "Quads"
  },
  {
    "id": "172",
    "name": "Smith Machine Squat",
    "category": "QUADS - SMITH MACHINE",
    "muscleGroup": "Quads"
  },
  {
    "id": "173",
    "name": "Walking Lunges (Quad-Focused, Barbell)",
    "category": "QUADS - BARBELL",
    "muscleGroup": "Quads"
  },
  {
    "id": "174",
    "name": "Walking Lunges (Quad-Focused, Bodyweight)",
    "category": "QUADS - BODYWEIGHT ONLY",
    "muscleGroup": "Quads"
  },
  {
    "id": "175",
    "name": "Walking Lunges (Quad-Focused, Dumbbell)",
    "category": "QUADS - DUMBBELL",
    "muscleGroup": "Quads"
  },
  {
    "id": "176",
    "name": "Arnold Press",
    "category": "SHOULDERS - DUMBBELL",
    "muscleGroup": "Shoulders"
  },
  {
    "id": "177",
    "name": "Barbell Facepull",
    "category": "SHOULDERS - BARBELL",
    "muscleGroup": "Shoulders"
  },
  {
    "id": "178",
    "name": "Barbell Front Raise",
    "category": "SHOULDERS - BARBELL",
    "muscleGroup": "Shoulders"
  },
  {
    "id": "179",
    "name": "Barbell Shoulder Press (Seated)",
    "category": "SHOULDERS - BARBELL",
    "muscleGroup": "Shoulders"
  },
  {
    "id": "180",
    "name": "Barbell Shoulder Press (Standing)",
    "category": "SHOULDERS - BARBELL",
    "muscleGroup": "Shoulders"
  },
  {
    "id": "181",
    "name": "Barbell Shrug",
    "category": "SHOULDERS - BARBELL",
    "muscleGroup": "Shoulders"
  },
  {
    "id": "182",
    "name": "Barbell Upright Row",
    "category": "SHOULDERS - BARBELL",
    "muscleGroup": "Shoulders"
  },
  {
    "id": "183",
    "name": "Cable Cross Body Lateral Raise",
    "category": "SHOULDERS - CABLE",
    "muscleGroup": "Shoulders"
  },
  {
    "id": "184",
    "name": "Cable Lateral Raise (Single-Arm)",
    "category": "SHOULDERS - CABLE",
    "muscleGroup": "Shoulders"
  },
  {
    "id": "185",
    "name": "Cable Rope Facepull",
    "category": "SHOULDERS - CABLE",
    "muscleGroup": "Shoulders"
  },
  {
    "id": "186",
    "name": "Cable Shrug",
    "category": "SHOULDERS - CABLE",
    "muscleGroup": "Shoulders"
  },
  {
    "id": "187",
    "name": "Cable Single Arm Rear Delt Raise",
    "category": "SHOULDERS - CABLE",
    "muscleGroup": "Shoulders"
  },
  {
    "id": "188",
    "name": "Cable Upright Row",
    "category": "SHOULDERS - CABLE",
    "muscleGroup": "Shoulders"
  },
  {
    "id": "189",
    "name": "Dumbbell Bent Lateral Raise",
    "category": "SHOULDERS - DUMBBELL",
    "muscleGroup": "Shoulders"
  },
  {
    "id": "190",
    "name": "Dumbbell Bent Over Shrug",
    "category": "SHOULDERS - DUMBBELL",
    "muscleGroup": "Shoulders"
  },
  {
    "id": "191",
    "name": "Dumbbell Facepull",
    "category": "SHOULDERS - DUMBBELL",
    "muscleGroup": "Shoulders"
  },
  {
    "id": "192",
    "name": "Dumbbell Facepull (Incline)",
    "category": "SHOULDERS - DUMBBELL",
    "muscleGroup": "Shoulders"
  },
  {
    "id": "193",
    "name": "Dumbbell Front Raise",
    "category": "SHOULDERS - DUMBBELL",
    "muscleGroup": "Shoulders"
  },
  {
    "id": "194",
    "name": "Dumbbell Lateral Raise",
    "category": "SHOULDERS - DUMBBELL",
    "muscleGroup": "Shoulders"
  },
  {
    "id": "195",
    "name": "Dumbbell Rear Delt Flys",
    "category": "SHOULDERS - DUMBBELL",
    "muscleGroup": "Shoulders"
  },
  {
    "id": "196",
    "name": "Dumbbell Shoulder Press (Seated)",
    "category": "SHOULDERS - DUMBBELL",
    "muscleGroup": "Shoulders"
  },
  {
    "id": "197",
    "name": "Dumbbell Shoulder Press (Standing)",
    "category": "SHOULDERS - DUMBBELL",
    "muscleGroup": "Shoulders"
  },
  {
    "id": "198",
    "name": "Dumbbell Shrug",
    "category": "SHOULDERS - DUMBBELL",
    "muscleGroup": "Shoulders"
  },
  {
    "id": "199",
    "name": "Dumbbell Shrug (Seated)",
    "category": "SHOULDERS - DUMBBELL",
    "muscleGroup": "Shoulders"
  },
  {
    "id": "200",
    "name": "Dumbbell Upright Row",
    "category": "SHOULDERS - DUMBBELL",
    "muscleGroup": "Shoulders"
  },
  {
    "id": "201",
    "name": "Machine Lateral Raise",
    "category": "SHOULDERS - MACHINE",
    "muscleGroup": "Shoulders"
  },
  {
    "id": "202",
    "name": "Machine Reverse Flye",
    "category": "SHOULDERS - MACHINE",
    "muscleGroup": "Shoulders"
  },
  {
    "id": "203",
    "name": "Machine Shoulder Press",
    "category": "SHOULDERS - MACHINE",
    "muscleGroup": "Shoulders"
  },
  {
    "id": "204",
    "name": "Smith Machine Shoulder Press (Seated)",
    "category": "SHOULDERS - SMITH MACHINE",
    "muscleGroup": "Shoulders"
  },
  {
    "id": "205",
    "name": "Smith Machine Upright Row",
    "category": "SHOULDERS - SMITH MACHINE",
    "muscleGroup": "Shoulders"
  },
  {
    "id": "206",
    "name": "Viking Press",
    "category": "SHOULDERS - MACHINE",
    "muscleGroup": "Shoulders"
  },
  {
    "id": "207",
    "name": "Cable Shrug",
    "category": "TRAPS - CABLE",
    "muscleGroup": "Traps"
  },
  {
    "id": "208",
    "name": "Dumbbell Shrug",
    "category": "TRAPS - DUMBBELL",
    "muscleGroup": "Traps"
  },
  {
    "id": "209",
    "name": "Dumbbell Shrug (Seated)",
    "category": "TRAPS - DUMBBELL",
    "muscleGroup": "Traps"
  },
  {
    "id": "210",
    "name": "Machine Shrug",
    "category": "TRAPS - MACHINE",
    "muscleGroup": "Traps"
  },
  {
    "id": "211",
    "name": "Smith Machine Shrug",
    "category": "TRAPS - SMITH MACHINE",
    "muscleGroup": "Traps"
  },
  {
    "id": "212",
    "name": "Assisted Dip",
    "category": "TRICEPS - MACHINE ASSISTANCE",
    "muscleGroup": "Triceps"
  },
  {
    "id": "213",
    "name": "Barbell Overhead Triceps Extension",
    "category": "TRICEPS - BARBELL",
    "muscleGroup": "Triceps"
  },
  {
    "id": "214",
    "name": "Barbell Overhead Triceps Extension (Seated)",
    "category": "TRICEPS - BARBELL",
    "muscleGroup": "Triceps"
  },
  {
    "id": "215",
    "name": "Barbell Skullcrusher",
    "category": "TRICEPS - BARBELL",
    "muscleGroup": "Triceps"
  },
  {
    "id": "216",
    "name": "Bench Press (Close Grip)",
    "category": "TRICEPS - BARBELL",
    "muscleGroup": "Triceps"
  },
  {
    "id": "217",
    "name": "Cable Overhead Tricep Extension (Single Arm)",
    "category": "TRICEPS - CABLE",
    "muscleGroup": "Triceps"
  },
  {
    "id": "218",
    "name": "Cable Overhead Triceps Extension",
    "category": "TRICEPS - CABLE",
    "muscleGroup": "Triceps"
  },
  {
    "id": "219",
    "name": "Cable Overhead Triceps Extension (Rope)",
    "category": "TRICEPS - CABLE",
    "muscleGroup": "Triceps"
  },
  {
    "id": "220",
    "name": "Cable Tricep Kickback",
    "category": "TRICEPS - CABLE",
    "muscleGroup": "Triceps"
  },
  {
    "id": "221",
    "name": "Cable Triceps Pushdown (Bar)",
    "category": "TRICEPS - CABLE",
    "muscleGroup": "Triceps"
  },
  {
    "id": "222",
    "name": "Cable Triceps Pushdown (Rope)",
    "category": "TRICEPS - CABLE",
    "muscleGroup": "Triceps"
  },
  {
    "id": "223",
    "name": "Cable Triceps Pushdown (Single-Arm)",
    "category": "TRICEPS - CABLE",
    "muscleGroup": "Triceps"
  },
  {
    "id": "224",
    "name": "Dip (Triceps-Focused)",
    "category": "TRICEPS - BODYWEIGHT ONLY",
    "muscleGroup": "Triceps"
  },
  {
    "id": "225",
    "name": "Dip (Weighted, Triceps-Focused)",
    "category": "TRICEPS - BODYWEIGHT LOADABLE",
    "muscleGroup": "Triceps"
  },
  {
    "id": "226",
    "name": "Dip Machine",
    "category": "TRICEPS - MACHINE",
    "muscleGroup": "Triceps"
  },
  {
    "id": "227",
    "name": "Dumbbell Overhead Extension",
    "category": "TRICEPS - DUMBBELL",
    "muscleGroup": "Triceps"
  },
  {
    "id": "228",
    "name": "Dumbbell Overhead Extension (Single-Arm)",
    "category": "TRICEPS - DUMBBELL",
    "muscleGroup": "Triceps"
  },
  {
    "id": "229",
    "name": "Dumbbell Overheard Extension",
    "category": "TRICEPS - DUMBBELL",
    "muscleGroup": "Triceps"
  },
  {
    "id": "230",
    "name": "Dumbbell Skullcrusher",
    "category": "TRICEPS - DUMBBELL",
    "muscleGroup": "Triceps"
  },
  {
    "id": "231",
    "name": "Ez Bar Overhead Triceps Extension",
    "category": "TRICEPS - BARBELL",
    "muscleGroup": "Triceps"
  },
  {
    "id": "232",
    "name": "Ez Bar Overhead Triceps Extension (Seated)",
    "category": "TRICEPS - BARBELL",
    "muscleGroup": "Triceps"
  },
  {
    "id": "233",
    "name": "Ez Bar Skullcrusher",
    "category": "TRICEPS - BARBELL",
    "muscleGroup": "Triceps"
  },
  {
    "id": "234",
    "name": "Machine Dips",
    "category": "TRICEPS - MACHINE",
    "muscleGroup": "Triceps"
  },
  {
    "id": "235",
    "name": "Machine Triceps Extension",
    "category": "TRICEPS - MACHINE",
    "muscleGroup": "Triceps"
  },
  {
    "id": "236",
    "name": "Machine Triceps Pushdown",
    "category": "TRICEPS - MACHINE",
    "muscleGroup": "Triceps"
  },
  {
    "id": "237",
    "name": "Smith Machine Skullcrusher",
    "category": "TRICEPS - SMITH MACHINE",
    "muscleGroup": "Triceps"
  },
  {
    "id": "238",
    "name": "Snatch",
    "category": "OLYMPIC LIFTS - BARBELL",
    "muscleGroup": "Olympic Lifts"
  },
  {
    "id": "239",
    "name": "Clean & Jerk",
    "category": "OLYMPIC LIFTS - BARBELL",
    "muscleGroup": "Olympic Lifts"
  },
  {
    "id": "240",
    "name": "Power Clean",
    "category": "OLYMPIC LIFTS - BARBELL",
    "muscleGroup": "Olympic Lifts"
  },
  {
    "id": "241",
    "name": "Power Clean",
    "category": "OLYMPIC LIFTS - DUMBBELL",
    "muscleGroup": "Olympic Lifts"
  },
  {
    "id": "242",
    "name": "Hang Clean",
    "category": "OLYMPIC LIFTS - BARBELL",
    "muscleGroup": "Olympic Lifts"
  },
  {
    "id": "243",
    "name": "Hang Clean",
    "category": "OLYMPIC LIFTS - DUMBBELL",
    "muscleGroup": "Olympic Lifts"
  },
  {
    "id": "244",
    "name": "Hang Power Clean",
    "category": "OLYMPIC LIFTS - BARBELL",
    "muscleGroup": "Olympic Lifts"
  },
  {
    "id": "245",
    "name": "Block Clean",
    "category": "OLYMPIC LIFTS - BARBELL",
    "muscleGroup": "Olympic Lifts"
  },
  {
    "id": "246",
    "name": "Muscle Clean",
    "category": "OLYMPIC LIFTS - BARBELL",
    "muscleGroup": "Olympic Lifts"
  },
  {
    "id": "247",
    "name": "Clean Pull",
    "category": "OLYMPIC LIFTS - BARBELL",
    "muscleGroup": "Olympic Lifts"
  },
  {
    "id": "248",
    "name": "High Pull",
    "category": "OLYMPIC LIFTS - BARBELL",
    "muscleGroup": "Olympic Lifts"
  },
  {
    "id": "249",
    "name": "Power Jerk",
    "category": "OLYMPIC LIFTS - BARBELL",
    "muscleGroup": "Olympic Lifts"
  },
  {
    "id": "250",
    "name": "Push Jerk",
    "category": "OLYMPIC LIFTS - BARBELL",
    "muscleGroup": "Olympic Lifts"
  },
  {
    "id": "251",
    "name": "Push Jerk",
    "category": "OLYMPIC LIFTS - DUMBBELL",
    "muscleGroup": "Olympic Lifts"
  },
  {
    "id": "252",
    "name": "Split Jerk",
    "category": "OLYMPIC LIFTS - BARBELL",
    "muscleGroup": "Olympic Lifts"
  },
  {
    "id": "253",
    "name": "Behind-The-Neck Jerk",
    "category": "OLYMPIC LIFTS - BARBELL",
    "muscleGroup": "Olympic Lifts"
  },
  {
    "id": "254",
    "name": "Power Snatch",
    "category": "OLYMPIC LIFTS - BARBELL",
    "muscleGroup": "Olympic Lifts"
  },
  {
    "id": "255",
    "name": "Power Snatch",
    "category": "OLYMPIC LIFTS - DUMBBELL",
    "muscleGroup": "Olympic Lifts"
  },
  {
    "id": "256",
    "name": "Hang Snatch",
    "category": "OLYMPIC LIFTS - BARBELL",
    "muscleGroup": "Olympic Lifts"
  },
  {
    "id": "257",
    "name": "Hang Power Snatch",
    "category": "OLYMPIC LIFTS - BARBELL",
    "muscleGroup": "Olympic Lifts"
  },
  {
    "id": "258",
    "name": "Block Snatch",
    "category": "OLYMPIC LIFTS - BARBELL",
    "muscleGroup": "Olympic Lifts"
  },
  {
    "id": "259",
    "name": "Muscle Snatch",
    "category": "OLYMPIC LIFTS - BARBELL",
    "muscleGroup": "Olympic Lifts"
  },
  {
    "id": "260",
    "name": "Snatch Pull",
    "category": "OLYMPIC LIFTS - BARBELL",
    "muscleGroup": "Olympic Lifts"
  },
  {
    "id": "261",
    "name": "High Pull (Snatch Grip)",
    "category": "OLYMPIC LIFTS - BARBELL",
    "muscleGroup": "Olympic Lifts"
  },
  {
    "id": "262",
    "name": "Front Squat (Olympic)",
    "category": "OLYMPIC LIFTS - BARBELL",
    "muscleGroup": "Olympic Lifts"
  },
  {
    "id": "263",
    "name": "Overhead Squat",
    "category": "OLYMPIC LIFTS - BARBELL",
    "muscleGroup": "Olympic Lifts"
  },
  {
    "id": "264",
    "name": "Tall Clean",
    "category": "OLYMPIC LIFTS - BARBELL",
    "muscleGroup": "Olympic Lifts"
  },
  {
    "id": "265",
    "name": "Tall Snatch",
    "category": "OLYMPIC LIFTS - BARBELL",
    "muscleGroup": "Olympic Lifts"
  },
  {
    "id": "266",
    "name": "Snatch Balance",
    "category": "OLYMPIC LIFTS - BARBELL",
    "muscleGroup": "Olympic Lifts"
  },
  {
    "id": "267",
    "name": "Jerk Recovery",
    "category": "OLYMPIC LIFTS - BARBELL",
    "muscleGroup": "Olympic Lifts"
  }
]
